#!/usr/bin/env node

var frameless = require('../lib/frameless');

//
// prompt users with a `are you sure` confirmation dialog
// end users can override this behavior by using the --yes option
//
frameless.confirm(true);

//
// single required option, `whoami`
//
frameless('whoami', function (opts) {
  //
  // silly is one of the levels to output a nicely formatted message
  // others are warn, info, and err
  //
  frameless.silly(opts);
});

//
// this module gets tests against `test/confirm-test.js`
// if you are curious about it feel free to take a peek in the source code
//