#!/usr/bin/env node

var clif = require('../lib/clif');

clif.confirm(false);

clif.relax('whoami', function (opts) {
  clif.warn(opts);
});

//
// this module gets tests against `test/confirm-test.js`
// if you are curious about it feel free to take a peek in the source code
//