#!/usr/bin/env node

var frameless = require('../lib/frameless');

frameless.confirm(false);

frameless('whoami', function (opts) {
  frameless.warn(opts);
});

//
// this module gets tests against `test/confirm-test.js`
// if you are curious about it feel free to take a peek in the source code
//