#!/usr/bin/env node

var frameless = require('../lib/frameless');

frameless.version = '1.0.1';
frameless.pp_version = function () { console.log(frameless.version); };

frameless('required', function (opts) {
  frameless.warn(opts.required);
});

//
// this module gets tests against `test/core-test.js`
// if you are curious about it feel free to take a peek in the source code
//