#!/usr/bin/env node
//
// sample frameless script to create a user against couchdb
//
var frameless = require('../lib/frameless')
  , url       = require('url')
  , nano      = require('nano')
  ;

//
// "frameless" allows you specify your own encryption key
// by default it will use ~/.ssh/id_rsa and 
// fallback to a key included in the code
//
frameless.key = 'd41d8cd98f00b204e9800998ecf8427e';

//
// turn on persisting options
//
frameless.save(true);

frameless(
    { name: 'host'     , required: false, 'default': 'localhost' }
  , { name: 'protocol' , required: false, 'default': 'http:'     }
  , { name: 'port'     , required: false, 'default': 5984        }
  , { name: 'username' , required: false             }
  , { name: 'password' , required: false             }
  , { name: 'usr-name' , required: true, save: false }
  , { name: 'usr-pwd'  , required: true, save: false }
  , { name: 'usr-email', required: true, save: false }, function (opts) {
    //
    // our uri object
    //
    var uri = 
      { port     : opts.port
      , protocol : opts.protocol
      , auth     : opts.username + ':' + opts.password
      , host     : opts.host
      };
    uri = url.format(uri) + '/_users';

    //
    // our user document
    //
    var user =
        { name         : opts['usr-name']
        , email        : opts['usr-email']
        , _id          : 'org.couchdb.user:' + opts['usr-name']
        , type         : 'user'
        , roles        : []
        , date         : new Date().toISOString()
        };

    var _users = nano(uri);
    console.log(_users);
});

//
// running a command with save will cause the command to save a dot file with
// the parameters introduced
//
// ```
// ./dotfiles --verbose
// ```
//
// feel free to inspect the contents of the file. you will find that password
// has been encrypted
//
// if you want to make use of this functionality in your cli I suggest you
// change the `cli.key`
//
// if you run the command again you will get the output imediately as
// frameless can get the data from the dot file
//
// ```
// ./dotfiles --yes
// ```
//
// you can change these values at command execution time by specifying the
// value
//
//
// if you don't wish to save some parameters you can specify the by using a
// 'no-save' key
//
// if you wish to reconfigure the full setup you can run `--config`
//
// if you have a custom key that you need encrypted that is not part of
// frameless.sensitive_info you can add it and frameless will start encrypting it
//
// create `--setup`
//
