#!/usr/bin/env node
//
// sample frameless script to delete couchdbs matching a pattern
//
// please run `npm install nano` to run this example
//
// curl localhost:5984/_all_dbs | \
//   ./usage/couchdb-delete-databases \
//   --pattern loggly \
//   --uri http://localhost:5984
//
var frameless = require('../lib/frameless')
  , nano      = require('nano')
  ;

frameless(
    { name: 'uri'      , required: false, 'default': 'http://localhost:5984' }
  , { name: 'pattern'  , required: true, 'default': 'testdb', save: false   },
  function (opts) {

    var server = nano(opts.uri)
      , rexp   = new RegExp(opts.pattern)
      ;

    server.db.list(function(err, body) {
      if(err || body.length === 0) {
        return frameless.err(err || 'No databases');
      }

      body.forEach(function(db_name) {
        if(rexp.test(db_name)) {
          frameless.info(db_name, 'destroyed');
          server.db.destroy(db_name, frameless.print);
        }
        else {
          frameless.info(db_name, 'ignored');
        }
      });
    });
});
