#!/usr/bin/env node

var frameless = require('../lib/frameless');

//
// simple interuption in a script that runs forever
//
frameless(function (opts) {
  //
  // warn is one of the levels to output a nicely formatted message
  // others are info, silly, and err
  //
  setInterval(function () {
    process.stdout.write((~~(Math.random() * 1e9)).toString(36));
  }, 100);
});

frameless.keypress('q', function () {
  console.log('\ncontrol+q: exiting');
  process.exit();
});