#!/usr/bin/env node

var clif = require('../lib/clif');

clif.version = require('../package').version;
clif.pp_version = function () { console.log(clif.version); };

clif.relax(function () {
  clif.silly(clif.reserved_options);
});