#!/usr/bin/env node

var frameless = require('../lib/frameless');

frameless('help', function (opts) {
  frameless.silly(frameless.reserved_options);
});

//
// this module gets tests against `test/reserved-test.js`
// if you are curious about it feel free to take a peek in the source code
//