#!/usr/bin/env node

var frameless = require('../lib/frameless');

//
// `--help` is a reserved option, so when you try to use it in your programs
// they will not work. you can override this behavior with some hacking around
// but i recomment aggainst it
//
frameless('help', function (opts) {
  frameless.silly(frameless.reserved_options);
});

//
// this module gets tests against `test/reserved-test.js`
// if you are curious about it feel free to take a peek in the source code
//